package ArknightsMod.Helper;

import ArknightsMod.Cards.Operator.AbstractOperatorCard;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.megacrit.cardcrawl.helpers.ImageMaster;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class ArknightsImageMaster {
    private static final Logger logger = LogManager.getLogger(ArknightsImageMaster.class.getName());
    private static TextureAtlas vfxAtlas;
    private static TextureAtlas charAtlas;
    private static TextureAtlas chenAtlas;
    public static TextureAtlas.AtlasRegion ANGEL_1;
    public static TextureAtlas.AtlasRegion ANGEL_2;
    public static TextureAtlas.AtlasRegion ANGEL_3;
    public static TextureAtlas.AtlasRegion POWERSTRIKE_1;
    public static TextureAtlas.AtlasRegion POWERSTRIKE_2;
    public static TextureAtlas.AtlasRegion POWERSTRIKE_3;
    public static TextureAtlas.AtlasRegion SVRASH_2;
    public static TextureAtlas.AtlasRegion SVRASH_3;
    public static TextureAtlas.AtlasRegion CHARGE_COST_1;
    public static TextureAtlas.AtlasRegion CHARGE_COST_2;
    public static TextureAtlas.AtlasRegion CHARGE_COST_3;
    public static TextureAtlas.AtlasRegion TEXAS_2;
    public static TextureAtlas.AtlasRegion EYJAFJALLA_1;
    public static TextureAtlas.AtlasRegion EYJAFJALLA_2;
    public static TextureAtlas.AtlasRegion EYJAFJALLA_3;
    public static TextureAtlas.AtlasRegion SPOT_1;
    public static TextureAtlas.AtlasRegion ANSEL_1;
    public static TextureAtlas.AtlasRegion MIDNIGHT_1;
    public static TextureAtlas.AtlasRegion QUICK_ATTACK_1;
    public static TextureAtlas.AtlasRegion CATAP_1;
    public static TextureAtlas.AtlasRegion ATK_UP_1;
    public static TextureAtlas.AtlasRegion ATK_UP_2;
    public static TextureAtlas.AtlasRegion ATK_UP_3;
    public static TextureAtlas.AtlasRegion HEAL_UP_1;
    public static TextureAtlas.AtlasRegion MATK_UP_1;
    public static TextureAtlas.AtlasRegion MATK_UP_2;
    public static TextureAtlas.AtlasRegion KROOS_1;
    public static TextureAtlas.AtlasRegion BLUEP_1;
    public static TextureAtlas.AtlasRegion BLUEP_2;
    public static TextureAtlas.AtlasRegion LISKARM_1;
    public static TextureAtlas.AtlasRegion LISKARM_2;
    public static TextureAtlas.AtlasRegion RED_1;
    public static TextureAtlas.AtlasRegion RED_2;
    public static TextureAtlas.AtlasRegion LAPPLAND_1;
    public static TextureAtlas.AtlasRegion LAPPLAND_2;
    public static TextureAtlas.AtlasRegion JESSICA_2;
    public static TextureAtlas.AtlasRegion HAZE_2;
    public static TextureAtlas.AtlasRegion GITANO_2;
    public static TextureAtlas.AtlasRegion CHEN_1;
    public static TextureAtlas.AtlasRegion CHEN_2;
    public static TextureAtlas.AtlasRegion CHEN_3;
    public static TextureAtlas.AtlasRegion GRAVEL_1;
    public static TextureAtlas.AtlasRegion GRAVEL_2;
    public static TextureAtlas.AtlasRegion MAYER_1;
    public static TextureAtlas.AtlasRegion MAYER_2;
    public static TextureAtlas.AtlasRegion SPECTER_2;
    public static TextureAtlas.AtlasRegion NEARL_1;
    public static TextureAtlas.AtlasRegion NEARL_2;
    public static TextureAtlas.AtlasRegion METEOR_1;
    public static TextureAtlas.AtlasRegion METEOR_2;
    public static TextureAtlas.AtlasRegion COURIER_2;
    public static TextureAtlas.AtlasRegion SCAVENGER_2;
    public static TextureAtlas.AtlasRegion EMPTY;

    public static TextureAtlas.AtlasRegion SKILL_READY;
    public static TextureAtlas.AtlasRegion ESCAPE;
    public static TextureAtlas.AtlasRegion ATTACK_COOLDOWN;
    public static TextureAtlas.AtlasRegion ATTACK;
    public static TextureAtlas.AtlasRegion STAR_1;
    public static TextureAtlas.AtlasRegion STAR_2;
    public static TextureAtlas.AtlasRegion STAR_3;
    public static TextureAtlas.AtlasRegion STAR_4;
    public static TextureAtlas.AtlasRegion STAR_5;
    public static TextureAtlas.AtlasRegion STAR_6;
    public static TextureAtlas.AtlasRegion TYPE_SPECIALIST;
    public static TextureAtlas.AtlasRegion TYPE_GUARD;
    public static TextureAtlas.AtlasRegion TYPE_MEDIC;
    public static TextureAtlas.AtlasRegion TYPE_VANGUARD;
    public static TextureAtlas.AtlasRegion TYPE_SNIPER;
    public static TextureAtlas.AtlasRegion TYPE_SUPPORTER;
    public static TextureAtlas.AtlasRegion TYPE_CASTER;
    public static TextureAtlas.AtlasRegion TYPE_DEFENDER;
    public static TextureAtlas.AtlasRegion OPERATOR_POSITION;

    public static Texture TICKET;
    public static Texture RECRUIT_SPECIALIST;
    public static Texture RECRUIT_GUARD;
    public static Texture RECRUIT_MEDIC;
    public static Texture RECRUIT_VANGUARD;
    public static Texture RECRUIT_SNIPER;
    public static Texture RECRUIT_SUPPORTER;
    public static Texture RECRUIT_CASTER;
    public static Texture RECRUIT_DEFENDER;


    public static TextureAtlas.AtlasRegion[] CHEN_LONG = new TextureAtlas.AtlasRegion[5];
    public static TextureAtlas.AtlasRegion[] CHEN_SKILL = new TextureAtlas.AtlasRegion[5];

    public ArknightsImageMaster(){}

    public static void initialize(){
        long startTime = System.currentTimeMillis();
        vfxAtlas = new TextureAtlas(Gdx.files.internal("ArkImg/skills/skills.atlas"));
        ANGEL_1 = vfxAtlas.findRegion("skill_icon_skchr_angel_1");
        ANGEL_2 = vfxAtlas.findRegion("skill_icon_skchr_angel_2");
        ANGEL_3 = vfxAtlas.findRegion("skill_icon_skchr_angel_3");
        POWERSTRIKE_1 = vfxAtlas.findRegion("skill_icon_skcom_powerstrike[1]");
        POWERSTRIKE_2 = vfxAtlas.findRegion("skill_icon_skcom_powerstrike[2]");
        POWERSTRIKE_3 = vfxAtlas.findRegion("skill_icon_skcom_powerstrike[3]");
        SVRASH_2 = vfxAtlas.findRegion("skill_icon_skchr_svrash_2");
        SVRASH_3 = vfxAtlas.findRegion("skill_icon_skchr_svrash_3");
        CHARGE_COST_1 = vfxAtlas.findRegion("skill_icon_skcom_charge_cost[1]");
        CHARGE_COST_2 = vfxAtlas.findRegion("skill_icon_skcom_charge_cost[2]");
        CHARGE_COST_3 = vfxAtlas.findRegion("skill_icon_skcom_charge_cost[3]");
        TEXAS_2 = vfxAtlas.findRegion("skill_icon_skchr_texas_2");
        EYJAFJALLA_1 = vfxAtlas.findRegion("skill_icon_skchr_amgoat_1");
        EYJAFJALLA_2 = vfxAtlas.findRegion("skill_icon_skchr_amgoat_2");
        EYJAFJALLA_3 = vfxAtlas.findRegion("skill_icon_skchr_amgoat_3");
        SPOT_1 = vfxAtlas.findRegion("skill_icon_skchr_spot_1");
        ANSEL_1 = vfxAtlas.findRegion("skill_icon_skcom_range_extend");
        MIDNIGHT_1 = vfxAtlas.findRegion("skill_icon_skcom_enchant[1]");
        QUICK_ATTACK_1 = vfxAtlas.findRegion("skill_icon_skcom_quickattack[1]");
        CATAP_1 = vfxAtlas.findRegion("skill_icon_skcom_blowrange_up[1]");
        ATK_UP_1 = vfxAtlas.findRegion("skill_icon_skcom_atk_up[1]");
        ATK_UP_2 = vfxAtlas.findRegion("skill_icon_skcom_atk_up[2]");
        ATK_UP_3 = vfxAtlas.findRegion("skill_icon_skcom_atk_up[3]");
        HEAL_UP_1 = vfxAtlas.findRegion("skill_icon_skcom_heal_up[1]");
        MATK_UP_1 = vfxAtlas.findRegion("skill_icon_skcom_magic_rage[1]");
        MATK_UP_2 = vfxAtlas.findRegion("skill_icon_skcom_magic_rage[2]");
        KROOS_1 = vfxAtlas.findRegion("skill_icon_skchr_kroos_1");
        BLUEP_1 = vfxAtlas.findRegion("skill_icon_skchr_bluep_1");
        BLUEP_2 = vfxAtlas.findRegion("skill_icon_skchr_bluep_2");
        LISKARM_1 = vfxAtlas.findRegion("skill_icon_skchr_liskam_1");
        LISKARM_2 = vfxAtlas.findRegion("skill_icon_skchr_liskam_2");
        RED_1 = vfxAtlas.findRegion("skill_icon_skchr_red_1");
        RED_2 = vfxAtlas.findRegion("skill_icon_skchr_red_2");
        LAPPLAND_1 = vfxAtlas.findRegion("skill_icon_skchr_whitew_1");
        LAPPLAND_2 = vfxAtlas.findRegion("skill_icon_skchr_whitew_2");
        JESSICA_2 = vfxAtlas.findRegion("skill_icon_skchr_jesica_2");
        HAZE_2 = vfxAtlas.findRegion("skill_icon_skchr_nights_2");
        GITANO_2 = vfxAtlas.findRegion("skill_icon_skchr_fmout_2");
        CHEN_1 = vfxAtlas.findRegion("skill_icon_skchr_chen_1");
        CHEN_2 = vfxAtlas.findRegion("skill_icon_skchr_chen_2");
        CHEN_3 = vfxAtlas.findRegion("skill_icon_skchr_chen_3");
        GRAVEL_1 = vfxAtlas.findRegion("skill_icon_skchr_gravel_1");
        GRAVEL_2 = vfxAtlas.findRegion("skill_icon_skchr_gravel_2");
        MAYER_1 = vfxAtlas.findRegion("skill_icon_skchr_otter_1");
        MAYER_2 = vfxAtlas.findRegion("skill_icon_skchr_otter_2");
        SPECTER_2 = vfxAtlas.findRegion("skill_icon_skchr_ghost_2");
        NEARL_1 = vfxAtlas.findRegion("skill_icon_skchr_nearl_1");
        NEARL_2 = vfxAtlas.findRegion("skill_icon_skchr_nearl_2");
        METEOR_1 = vfxAtlas.findRegion("skill_icon_skchr_shotst_1");
        METEOR_2 = vfxAtlas.findRegion("skill_icon_skchr_shotst_2");
        COURIER_2 = vfxAtlas.findRegion("skill_icon_skchr_blackd_2");
        SCAVENGER_2 = vfxAtlas.findRegion("skill_icon_skchr_scave_2");
        EMPTY = new TextureAtlas.AtlasRegion(ImageMaster.loadImage("ArkImg/skills/empty.png"),0, 0, 128, 128);

        charAtlas = new TextureAtlas(Gdx.files.internal("ArkImg/char/char.atlas"));
        SKILL_READY = charAtlas.findRegion("ready");
        ESCAPE = charAtlas.findRegion("escape");
        ATTACK_COOLDOWN = charAtlas.findRegion("frame11");
        ATTACK = charAtlas.findRegion("frame10");
        STAR_1 = charAtlas.findRegion("star", 1);
        STAR_2 = charAtlas.findRegion("star", 2);
        STAR_3 = charAtlas.findRegion("star", 3);
        STAR_4 = charAtlas.findRegion("star", 4);
        STAR_5 = charAtlas.findRegion("star", 5);
        STAR_6 = charAtlas.findRegion("star", 6);
        TYPE_CASTER = charAtlas.findRegion("caster");
        TYPE_DEFENDER = charAtlas.findRegion("defender");
        TYPE_GUARD = charAtlas.findRegion("guard");
        TYPE_MEDIC = charAtlas.findRegion("medic");
        TYPE_SNIPER = charAtlas.findRegion("sniper");
        TYPE_SPECIALIST = charAtlas.findRegion("specialist");
        TYPE_SUPPORTER = charAtlas.findRegion("supporter");
        TYPE_VANGUARD = charAtlas.findRegion("vanguard");
        OPERATOR_POSITION = charAtlas.findRegion("position");

        chenAtlas = new TextureAtlas(Gdx.files.internal("ArkImg/vfx/chen_skill.atlas"));
        CHEN_LONG[0] = chenAtlas.findRegion("frame0");
        CHEN_LONG[1] = chenAtlas.findRegion("frame4");
        CHEN_LONG[2] = chenAtlas.findRegion("frame1");
        CHEN_LONG[3] = chenAtlas.findRegion("frame2");
        CHEN_LONG[4] = chenAtlas.findRegion("frame3");
        CHEN_SKILL[0] = chenAtlas.findRegion("chen", 1);
        CHEN_SKILL[1] = chenAtlas.findRegion("chen", 2);
        CHEN_SKILL[2] = chenAtlas.findRegion("chen", 3);
        CHEN_SKILL[3] = chenAtlas.findRegion("chen", 4);
        CHEN_SKILL[4] = chenAtlas.findRegion("chen", 5);

        TICKET = ImageMaster.loadImage("ArkImg/UI/recruit_ticket.png");
        RECRUIT_SPECIALIST = ImageMaster.loadImage("ArkImg/UI/specialist_recruit.png");
        RECRUIT_GUARD = ImageMaster.loadImage("ArkImg/UI/guard_recruit.png");
        RECRUIT_MEDIC = ImageMaster.loadImage("ArkImg/UI/medic_recruit.png");
        RECRUIT_VANGUARD = ImageMaster.loadImage("ArkImg/UI/vanguard_recruit.png");
        RECRUIT_SNIPER = ImageMaster.loadImage("ArkImg/UI/sniper_recruit.png");
        RECRUIT_SUPPORTER = ImageMaster.loadImage("ArkImg/UI/supporter_recruit.png");
        RECRUIT_CASTER = ImageMaster.loadImage("ArkImg/UI/caster_recruit.png");
        RECRUIT_DEFENDER = ImageMaster.loadImage("ArkImg/UI/defender_recruit.png");

        logger.info("Texture load time: " + (System.currentTimeMillis() - startTime) + "ms");
        AbstractOperatorCard.init();
    }
}
